server:
  port: 8080

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
  application:
    name: talent-api-gateway

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka